apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelmon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelmon
  template:
    metadata:
      labels:
        app: pixelmon
    spec:
      containers:
        - env:
          - name: EULA
            value: "TRUE"
          name: pixelmon
          image: itzg/minecraft-server
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              hostPort: 25565
          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 2000m
              memory: 4000Mi
          volumeMounts:
            - mountPath: /data
              name: pixelmondata
      volumes:
        - name: pixelmondata
          persistentVolumeClaim:
            claimName: pixelmon-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pixelmon-pv-volume
  labels:
    type: local
    app: pixelmon
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "~/mc-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pixelmon-pv-claim
  labels:
    app: pixelmon
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
