apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: default
### START COPY FROM THE HELM INSTALL RANCHER ISSUER IN THE CATTLE NAME SPACE ###
spec:
  acme:
    email: jameswitts92@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
### END COPY ###