apiVersion: apps/v1
kind: Deployment
metadata:
  name: paintapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paintapp
  template:
    metadata:
      labels:
        app: paintapp
    spec:
      containers:
        - name: paintapp
          image: jaynericguy/paintapp-django-armv8:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 500m
              memory: 1500Mi
