apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paintapp-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:
    - host: paint.junder.app
      http:
        paths:
          - path: /paintapp
            pathType: Prefix
            backend:
              service:
                name: paintapp-service
                port:
                  number: 80
  tls:
    - hosts:
      - paint.junder.app
      secretName: junderapp