apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlurby
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zlurby
  template:
    metadata:
      labels:
        app: zlurby
    spec:
      containers:
        - name: zlurby
          image: jaynericguy/zlurby:latest
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
            - 169.254.20.10
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1000Mi