apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.3-alpine
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
          - name: POSTGRES_PASSWORD
            value: "junder"
          - name: POSTGRES_USER
            value: "junder"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 2000Mi
    #volumes:
    #- name: junderpostgres
      #hostPath:
        # directory location on host
        #path: /home/pi/junderpostgres
        # this field is optional
        #type: Directory

